apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-proxy
  namespace: teamdigisos
  labels:
    team: teamdigisos
  annotations:
    nais.io/run-as-group: "0"
    nais.io/read-only-file-system: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "150M"
spec:
  image: {{image}}
  port: 8080
  ingresses:
{{#each ingresses}}
    - "{{this}}"
{{/each}}
  prometheus:
    enabled: false
    path: /prometheus
  liveness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isAlive
    initialDelay: 20
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 1m
      memory: 32Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  webproxy: false
  env:
    - name: PORT
      value: "8080"
    - name: DOMENE_PA_UTSIDEN
      value: {{domene_pa_utsiden}}
    - name: DOMENE_PA_INNSIDEN
      value: {{domene_pa_innsiden}}
