name: Deploy dev
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create artifact version
        id: artifact-version
        uses: navikt/sosialhjelp-ci/actions/create-artifact-version@master
      - name: Sett env variabler
        run: |
          PROJECT_NAME=$(echo ${{ github.repository }} | cut -d/ -f2)
          echo "IMAGE=ghcr.io/${{ github.repository }}/$PROJECT_NAME:${{ steps.artifact-version.outputs.version }}" >> $GITHUB_ENV
          echo "CONFIG_FILE=${{ github.event.inputs.config-file-name }}" >> $GITHUB_ENV
      - name: Deploy til GCP
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: nais.yaml
          CLUSTER: dev-gcp
          VARS: nais/dev.json
          REF: ${{ steps.artifact-version.outputs.version }}
          PRINT_PAYLOAD: true
          IMAGE: ${{ env.IMAGE }}
